<a href="https://colab.research.google.com/github/liz8888-ai/weekN2_lab/blob/main/A85204925001_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
# Session 2: Graded Exercises (100 marks, 60 minutes)
#A85204925001

**Example of how to answer:**

```python
total = None  # YOUR CODE HERE      <- before
total = a + b  # YOUR CODE HERE     <- after
```

(Run the setup cell below first.)

In [16]:
import numpy as np
import time

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


In [17]:
import numpy as np

def show(label, value):
    # Prints your answer, or a reminder if you have not answered yet.
    if value is None:
        print(f"{label}: not answered yet")
    else:
        print(f"{label}:\n{value}\n")

## Exercise 1: Creating arrays in 1-D, 2-D and 3-D (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | `v`: a 1-D array with the values 3, 6, 9, 12, 15. | 2 |
| (b) | `M`: a 2-D array with 2 rows: `[1, 2, 3]` and `[4, 5, 6]`. | 2 |
| (c) | `T`: a 3-D array of shape `(2, 2, 3)` that contains the numbers 1 to 12. Use `np.arange` and `reshape`. | 2 |
| (d) | `Z`: a 3x3 matrix of zeros. `O`: a 1-D array of five ones. | 2 |
| (e) | `v_ndim`, `M_ndim`, `T_ndim`: the number of dimensions of `v`, `M` and `T`. `T_shape`: the shape of `T`. | 2 |

In [21]:
# (a)
v = np.array([3, 6, 9, 12, 15])  # YOUR CODE HERE

# (b)
M = np.array([[1, 2, 3], [4, 5, 6]])   # YOUR CODE HERE

# (c)
T = np.arange(1, 13).reshape(2, 2, 3)   # YOUR CODE HERE

# (d)
Z = np.zeros((3, 3))  # YOUR CODE HERE
O = np.ones(5)   # YOUR CODE HERE

# (e)
v_ndim = v.ndim  # YOUR CODE HERE
M_ndim = M.ndim  # YOUR CODE HERE
T_ndim = T.ndim  # YOUR CODE HERE
T_shape = T.shape  # YOUR CODE HERE

show("v", v)
show("M", M)
show("T", T)
show("Z", Z)
show("O", O)
show("v_ndim", v_ndim)
show("M_ndim", M_ndim)
show("T_ndim", T_ndim)
show("T_shape", T_shape)

v:
[ 3  6  9 12 15]

M:
[[1 2 3]
 [4 5 6]]

T:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Z:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

O:
[1. 1. 1. 1. 1.]

v_ndim:
1

M_ndim:
2

T_ndim:
3

T_shape:
(2, 2, 3)



## Exercise 2: Selecting from 1-D and 2-D arrays (10 marks)

`rain` is the rainfall (mm) for 7 days (1-D).
`scores` holds the marks of 4 students (rows 0 to 3) in 3 subjects (columns 0 to 2: Math, Physics, English).

| Part | Task | Marks |
|---|---|---|
| (a) | `first_day` and `last_day`: the first and the last value of `rain`. | 2 |
| (b) | `mid_days`: the rainfall of the days with index 2, 3 and 4. | 2 |
| (c) | `student1`: all marks of student 1 (a whole row). | 2 |
| (d) | `physics`: the Physics marks of all students (a whole column). | 2 |
| (e) | `s3_math`: the Math mark of student 3. `top_left`: the first two students in the first two subjects (a 2x2 matrix). | 2 |

In [19]:
rain = np.array([0, 12, 5, 30, 8, 0, 17])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

first_day = rain[0]  # YOUR CODE HERE

last_day = rain[-1]  # YOUR CODE HERE

mid_days = rain[2:5]  # YOUR CODE HERE

student1 = scores[1, :]  # YOUR CODE HERE

physics = scores[:, 1]  # YOUR CODE HERE

s3_math = scores[3, 0]  # YOUR CODE HERE

top_left = scores[0:2, 0:2]  # YOUR CODE HERE

show("first_day", first_day)
show("last_day", last_day)
show("mid_days", mid_days)
show("student1", student1)
show("physics", physics)
show("s3_math", s3_math)
show("top_left", top_left)

first_day:
0

last_day:
17

mid_days:
[ 5 30  8]

student1:
[85 79 90]

physics:
[88 79 71 84]

s3_math:
93

top_left:
[[72 88]
 [85 79]]



## Exercise 3: Selecting from a 3-D array (10 marks)

`sales` is a 3-D array with shape `(2, 3, 4)`:

- dimension 0: the **week** (0 or 1)
- dimension 1: the **store** (0, 1 or 2)
- dimension 2: the **product** (0, 1, 2 or 3)

So `sales[w, s, p]` is the number of units of product `p` sold in store `s` during week `w`.

| Part | Task | Marks |
|---|---|---|
| (a) | `sales_ndim` and `sales_shape`: the number of dimensions and the shape of `sales`. | 2 |
| (b) | `week0`: all sales of week 0 (a 3x4 matrix). | 2 |
| (c) | `w1_store2`: the sales of store 2 in week 1 (4 values). | 2 |
| (d) | `one_value`: the units of product 3 sold in store 0 during week 0. | 2 |
| (e) | `w1_product0`: the sales of product 0 in every store during week 1 (3 values). | 2 |

In [20]:
sales = np.array([[[12,  7, 30,  4],
                   [ 9, 15, 22,  6],
                   [20,  3, 18, 11]],

                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])

sales_ndim = sales.ndim  # YOUR CODE HERE

sales_shape = sales.shape  # YOUR CODE HERE

week0 = sales[0, :, :]  # YOUR CODE HERE

w1_store2 = sales[1, 2, :]  # YOUR CODE HERE

one_value = sales[0, 0, 3]  # YOUR CODE HERE

w1_product0 = sales[1, :, 0]  # YOUR CODE HERE

show("sales_ndim", sales_ndim)
show("sales_shape", sales_shape)
show("week0", week0)
show("w1_store2", w1_store2)
show("one_value", one_value)
show("w1_product0", w1_product0)

sales_ndim:
3

sales_shape:
(2, 3, 4)

week0:
[[12  7 30  4]
 [ 9 15 22  6]
 [20  3 18 11]]

w1_store2:
[17  8 21 13]

one_value:
4

w1_product0:
[14 11 17]



## Exercise 4: Addition and subtraction (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `ab_sum` is `a` plus `b`, and `ab_diff` is `b` minus `a`. | 2 |
| (b) | 2-D: `total` is the sales of `jan` and `feb` added together, and `change` is `feb` minus `jan`. | 2 |
| (c) | 3-D: `T_sum` is `T1` plus `T2`. | 2 |
| (d) | `jan_plus10`: add 10 to every value of `jan`. | 2 |
| (e) | `jan_bonus`: add the 1-D array `bonus` to every row of `jan`. | 2 |

In [8]:
a = np.array([4, 8, 15, 16])
b = np.array([10, 20, 30, 40])

jan = np.array([[5, 3, 8],
                [2, 7, 4]])
feb = np.array([[6, 1, 9],
                [4, 7, 2]])

T1 = np.arange(8).reshape(2, 2, 2)
T2 = np.full((2, 2, 2), 10)

bonus = np.array([1, 0, 5])

ab_sum = a + b  # YOUR CODE HERE

ab_diff = b - a  # YOUR CODE HERE

total = jan + feb  # YOUR CODE HERE

change = feb - jan  # YOUR CODE HERE

T_sum = T1 + T2  # YOUR CODE HERE

jan_plus10 = jan + 10  # YOUR CODE HERE

jan_bonus = jan + bonus  # YOUR CODE HERE
show("ab_sum", ab_sum)
show("ab_diff", ab_diff)
show("total", total)
show("change", change)
show("T_sum", T_sum)
show("jan_plus10", jan_plus10)
show("jan_bonus", jan_bonus)

ab_sum:
[14 28 45 56]

ab_diff:
[ 6 12 15 24]

total:
[[11  4 17]
 [ 6 14  6]]

change:
[[ 1 -2  1]
 [ 2  0 -2]]

T_sum:
[[[10 11]
  [12 13]]

 [[14 15]
  [16 17]]]

jan_plus10:
[[15 13 18]
 [12 17 14]]

jan_bonus:
[[ 6  3 13]
 [ 3  7  9]]



## Exercise 5: Multiplication (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `cost` is the cost of each item (`price` times `qty`, element-wise). | 2 |
| (b) | 1-D: `bill` is the total bill, computed as the **dot product** of `price` and `qty`. | 2 |
| (c) | 2-D: `elem` is the element-wise product of `A` and `B`. `prod` is the matrix product of `A` and `B`. | 2 |
| (d) | `PC` is the matrix product of `P` (2x3) and `C` (3x2), and `PC_shape` is its shape. | 2 |
| (e) | Written: explain why `C @ C` gives an error. | 2 |

In [12]:
price = np.array([2.5, 4.0, 1.0, 10.0])
qty = np.array([4, 2, 10, 1])

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[2, 0],
              [1, 3]])

P = np.array([[1, 2, 3],
              [4, 5, 6]])
C = np.array([[1, 0],
              [2, 1],
              [0, 3]])

cost = price * qty  # YOUR CODE HERE

bill = price @ qty  # YOUR CODE HERE

elem = A * B  #  YOUR CODE HERE
prod = A @ B  # YOUR CODE HERE

PC = P @ C  # YOUR CODE HERE
PC_shape = PC.shape  # YOUR CODE HERE

print("cost", cost)
print("bill", bill)
print("elem", elem)
print("prod", prod)
print("PC", PC)
print("PC_shape", PC_shape)

cost:
[10.  8. 10. 10.]

bill:
38.0

elem:
[[ 2  0]
 [ 3 12]]

prod:
[[ 4  6]
 [10 12]]

PC:
[[ 5 11]
 [14 23]]

PC_shape:
(2, 2)



**(e) My answer:**

In [ ]:
CC = C @ C

print('CC',)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

[link text](https://)*C @ C gives an error because C is a 3x2 matrix,  the number of columns in the first matrix should be equal to the number of rows in the second matrix. Here, 2 does not equal 3..*

## Exercise 6: Absolute values and negation (10 marks)

`err` is a 1-D array of prediction errors, `D` is a 2-D array and `D3` is a 3-D array.
`y_true` and `y_pred` are true and predicted values of a model.

| Part | Task | Marks |
|---|---|---|
| (a) | `abs_err`: the absolute values of `err`. | 2 |
| (b) | `neg_D`: the negation of `D`. | 2 |
| (c) | `abs_D3`: the absolute values of `D3`. | 2 |
| (d) | `mae`: the Mean Absolute Error between `y_true` and `y_pred`. | 2 |
| (e) | `n_big`: how many values of `err` have an absolute value greater than 2. | 2 |

In [13]:
err = np.array([-1.5, 3.0, -2.5, 0.5, 4.0, -0.5])

D = np.array([[ 3, -1],
              [-4,  2]])

D3 = np.array([[[-1,  2], [ 3, -4]],
               [[ 5, -6], [-7,  8]]])

y_true = np.array([10.0, 12.0, 9.0, 15.0])
y_pred = np.array([11.0, 10.0, 9.5, 14.0])

abs_err = np.abs(err)  # YOUR CODE HERE

neg_D = (-D)  # YOUR CODE HERE

abs_D3 = np.abs(D3) # YOUR CODE HERE

mae = np.mean(np.abs(y_true - y_pred))  # YOUR CODE HERE

n_big = np.prod(abs_err.shape) > 2  # YOUR CODE HERE

print("abs_err", abs_err)
print("neg_D", neg_D)
print("abs_D3", abs_D3)
print("mae", mae)
print("n_big", n_big)

abs_err [1.5 3.  2.5 0.5 4.  0.5]
neg_D [[-3  1]
 [ 4 -2]]
abs_D3 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
mae 1.125
n_big True


## Exercise 7: Adding and removing elements, rows and columns (10 marks)

Each part starts from the **original** arrays given below.

| Part | Task | Marks |
|---|---|---|
| (a) | 1-D: `ages_add`: add the value 50 to the end of `ages`. | 2 |
| (b) | 1-D: `ages_del`: remove the element at index 1 from `ages`. | 2 |
| (c) | 2-D: `H_row`: add `new_house` as a new last row of `H`. | 2 |
| (d) | 2-D: `H_col`: add `floors` as a new last column of `H`. | 2 |
| (e) | `H_no_first_col`: remove column 0 from `H`. `H3`: stack `H` and `H2` into a 3-D array. | 2 |

In [14]:
ages = np.array([21, 19, 23, 20])

# 3 houses, 2 features: area (m^2) and number of rooms
H = np.array([[ 85, 2],
              [150, 4],
              [ 60, 1]])
H2 = np.array([[ 90, 3],
               [120, 3],
               [ 70, 2]])

new_house = np.array([110, 3])
floors = np.array([2, 5, 1])

new_house = np.array([110, 3])
floors = np.array([2, 5, 1])

ages_add = np.append(ages, 50)  # YOUR CODE HERE

ages_del = np.delete(ages, 1)  # YOUR CODE HERE

H_row = np.vstack([H, [20, 15]])  # YOUR CODE HERE

H_col = np.column_stack([H, [12, 7, 6]])  # YOUR CODE HERE

H_no_first_col = np.delete(H, 0, axis=1) # YOUR CODE HERE
H3 = np.stack([H, H2])  # YOUR CODE HERE

show("ages_add", ages_add)
show("ages_del", ages_del)
show("H_row", H_row)
show("H_col", H_col)
show("H_no_first_col", H_no_first_col)
show("H3", H3)
show("H3 shape", None if H3 is None else H3.shape)

ages_add:
[21 19 23 20 50]

ages_del:
[21 23 20]

H_row:
[[ 85   2]
 [150   4]
 [ 60   1]
 [ 20  15]]

H_col:
[[ 85   2  12]
 [150   4   7]
 [ 60   1   6]]

H_no_first_col:
[[2]
 [4]
 [1]]

H3:
[[[ 85   2]
  [150   4]
  [ 60   1]]

 [[ 90   3]
  [120   3]
  [ 70   2]]]

H3 shape:
(2, 3, 2)



## Exercise 8: Maximum, minimum and sum (10 marks)

`temps` is the temperature for 7 days (1-D).
`scores` is the same 4x3 marks table as in Exercise 2 (rows are students, columns are Math, Physics, English).
`sales` is the same 3-D array as in Exercise 3.

| Part | Task | Marks |
|---|---|---|
| (a) | `t_max`, `t_min`, `t_sum`: the highest, lowest and total of `temps`. | 2 |
| (b) | `hottest_day`: the **index** of the highest temperature. | 2 |
| (c) | `student_total`: the total marks of each student (4 values). | 2 |
| (d) | `subject_best`: the highest mark in each subject (3 values). | 2 |
| (e) | `class_mean`: the average of the whole `scores` table. `all_sales`: the total of all values in `sales`. | 2 |

In [ ]:
temps = np.array([18, 21, 25, 23, 27, 16, 20])

scores = np.array([[72, 88, 65],
                   [85, 79, 90],
                   [60, 71, 74],
                   [93, 84, 58]])

sales = np.array([[[12,  7, 30,  4],
                   [ 9, 15, 22,  6],
                   [20,  3, 18, 11]],
                  [[14,  5, 28,  9],
                   [11, 15, 25,  2],
                   [17,  8, 21, 13]]])

t_max = temps.max() # YOUR CODE HERE
t_min = temps.min()  # YOUR CODE HERE
t_sum = temps.sum()  # YOUR CODE HERE

hottest_day = temps.argmax()  # YOUR CODE HERE

student_total = scores.sum(axis=1)  # YOUR CODE HERE

subject_best = scores.max(axis=0)  # YOUR CODE HERE

class_mean = scores.mean(axis=0)  # YOUR CODE HERE
all_sales = sales.sum()  # YOUR CODE HERE

show("t_max", t_max)
show("t_min", t_min)
show("t_sum", t_sum)
show("hottest_day", hottest_day)
show("student_total", student_total)
show("subject_best", subject_best)
show("class_mean", class_mean)
show("all_sales", all_sales)

## Exercise 9: Transpose (10 marks)

| Part | Task | Marks |
|---|---|---|
| (a) | `N_T`: the transpose of `N`, and `N_T_shape`: its shape. | 2 |
| (b) | `u_T_shape`: the shape of the transpose of the 1-D array `u`. Then, in the written cell, explain in one sentence why the shape did or did not change. | 2 |
| (c) | `r_T`: the transpose of the 2-D row `r`, and `r_T_shape`: its shape. | 2 |
| (d) | `back`: `True` if transposing `N` twice gives `N` again. Use `np.array_equal`. | 2 |
| (e) | `G`: the matrix product of `N` transposed with `N` (that is, `N.T @ N`), and `G_shape`: its shape. | 2 |

In [ ]:
N = np.array([[1, 2],
              [3, 4],
              [5, 6]])          # shape (3, 2)

u = np.array([7, 8, 9])         # 1-D

r = np.array([[1, 2, 3, 4]])    # 2-D, shape (1, 4)

N_T = N.T  # YOUR CODE HERE
N_T_shape = N.T.shape  # YOUR CODE HERE

u_T_shape = u.T.shape  # YOUR CODE HERE

r_T = r.T  # YOUR CODE HERE
r_T_shape = r.T.shape  # YOUR CODE HERE

back = N.T.T  # YOUR CODE HERE

G = N.T @ N  # YOUR CODE HERE
G_shape = G.shape  # YOUR CODE HERE

show("N_T", N_T)
show("N_T_shape", N_T_shape)
show("u_T_shape", u_T_shape)
show("r_T", r_T)
show("r_T_shape", r_T_shape)
show("back", back)
show("G", G)
show("G_shape", G_shape)

**(b) My answer:**

*The shape did not change because transposing a 1-D array does not change its dimensions.*

## Exercise 10: Vectorized arithmetic, a small prediction model (10 marks)

Do **not** use `for` loops in this exercise.

A shop predicts its daily sales (in units) from two features: the temperature and the number of visitors. The model is $\hat{y} = X w + b$.

| Part | Task | Marks |
|---|---|---|
| (a) | `celsius_to_f`: convert the 1-D array `celsius` to Fahrenheit using $F = C \times 1.8 + 32$. | 2 |
| (b) | `squares`: the square of every value in `nums`, and `sum_squares`: their total. | 2 |
| (c) | `y_hat`: the predictions of the model for all 5 days, using `X`, `w` and `b`. | 2 |
| (d) | `errors`: the true values `y` minus the predictions `y_hat`. | 2 |
| (e) | `mse`: the Mean Squared Error, the average of the squared errors. | 2 |

In [15]:
celsius = np.array([0, 10, 20, 30, 40])

nums = np.array([1, 2, 3, 4, 5, 6])

# 5 days, 2 features: temperature and visitors (in hundreds)
X = np.array([[20, 3],
              [25, 5],
              [18, 2],
              [30, 6],
              [22, 4]])
y = np.array([52, 75, 40, 96, 60])   # true sales

w = np.array([1.5, 8.0])
b = 2.0

celsius_to_f = celsius * 1.8 + 32  # YOUR CODE HERE

squares = np.square(nums)  # YOUR CODE HERE

sum_squares = squares.sum()  # YOUR CODE HERE

y_hat = X @ w + b  # YOUR CODE HERE

errors = y - y_hat  # YOUR CODE HERE

mse = np.mean(errors ** 2)  # YOUR CODE HERE

show("celsius_to_f", celsius_to_f)
show("squares", squares)
show("sum_squares", sum_squares)
show("y_hat", y_hat)
show("errors", errors)
show("mse", mse)

celsius_to_f:
[ 32.  50.  68.  86. 104.]

squares:
[ 1  4  9 16 25 36]

sum_squares:
91

y_hat:
[56.  79.5 45.  95.  67. ]

errors:
[-4.  -4.5 -5.   1.  -7. ]

mse:
22.25

